require 'berkshelf'
require 'googl'
require 'octokit'
require 'ridley'
require 'terminal-table'
require 'thor'

require_relative 'taste/cli'
require_relative 'taste/changelog'
require_relative 'taste/dependency'
require_relative 'taste/dependency_checker'
require_relative 'taste/display'
require_relative 'taste/symbols'
require_relative 'taste/version'
